apiVersion: batch/v1
kind: Job
metadata:
  name: busybox-job
spec:
  template:
    metadata:
      name: busybox
    spec:
      restartPolicy: Never
      containers:
      - name: busybox
        image: busybox:musl
        command: ["sleep", "120"]